export const platforms = [
  { code: "PC", name: "PC" },
  { code: "PS4", name: "PS4" },
  { code: "Xbox", name: "Xbox" },
  { code: "Nintendo", name: "Nintendo" },
  { code: "PS5", name: "PS5" },
];

export const categories = [
  { code: "Game Item", name: "Game Item" },
  { code: "Game Boosting/Coaching", name: "Game Boosting/Coaching" },
  { code: "Game Coins", name: "Game Coins" },
  { code: "Gift cards and Top up", name: "Gift cards and Top up" },
  { code: "Game account", name: "Game account" },
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini (fmr. 'Swaziland')",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
]

export const regions = [
  { code: "US", name: "US" },
  { code: "Europe", name: "Europe" },
  { code: "Great Britain", name: "Great Britain" },
  { code: "South Korea", name: "South Korea" },
  { code: "Russia", name: "Russia" },
  { code: "Canada", name: "Canada" },
  { code: "Australia", name: "Australia" },
  { code: "UAE", name: "UAE" },
  { code: "Singapore", name: "Singapore" },
  { code: "Kuwait", name: "Kuwait" },
  { code: "South Africa", name: "South Africa" },
  { code: "Vietnam", name: "Vietnam" },
  { code: "Argentina", name: "Argentina" },
  { code: "Bahrain", name: "Bahrain" },
  { code: "Brazil", name: "Brazil" },
  { code: "Chile", name: "Chile" },
  { code: "Colombia", name: "Colombia" },
  { code: "GLOBAL", name: "Global" },
  { code: "Hong Kong", name: "Hong Kong" },
  { code: "Indonesia", name: "Indonesia" }, 
  {code:"India",name:"India"},
  { code: "Italy", name: "Italy" },
  { code: "Japan", name: "Japan" },
  { code: "Mexico", name: "Mexico" },
  { code: "Myanmar", name: "Myanmar" },
  { code: "Oman", name: "Oman" },
  { code: "Peru", name: "Peru" },
  { code: "Philippines", name: "Philippines" },
  { code: "Qatar", name: "Qatar" },
  { code: "Thailand", name: "Thailand" },
  { code: "Turkey", name: "Turkey" },
  { code: "Taiwan", name: "Taiwan" },
  { code: "Ukraine", name: "Ukraine" },
  { code: "Saudi Arabia", name: "Saudi Arabia" },
];

export const currencies = [
  { code: "USD", name: "USD" },
  { code: "EUR", name: "EUR" },
  { code: "GBP", name: "GBP" },
  { code: "KRW", name: "KRW" },
  { code: "RUB", name: "RUB" },
  { code: "CAD", name: "CAD" },
  { code: "AUD", name: "AUD" },
  { code: "AED", name: "AED" },
  { code: "SGD", name: "SGD" },
  { code: "KWD", name: "KWD" },
  { code: "ZAR", name: "ZAR" },
  { code: "VND", name: "VND" },
  { code: "ARS", name: "ARS" },
  { code: "BHD", name: "BHD" },
  { code: "BRL", name: "BRL" },
  { code: "CLP", name: "CLP" },
  { code: "COP", name: "COP" },
  { code: "XXX", name: "XXX" },
  { code: "HKD", name: "HKD" },
  { code: "IDR", name: "IDR" },
  { code: "INR", name: "INR" },
  { code: "JPY", name: "JPY" },
  { code: "MXN", name: "MXN" },
  { code: "MMK", name: "MMK" },
  { code: "OMR", name: "OMR" },
  { code: "PEN", name: "PEN" },
  { code: "PHP", name: "PHP" },
  { code: "QAR", name: "QAR" },
  { code: "THB", name: "THB" },
  { code: "TRY", name: "TRY" },
  { code: "TWD", name: "TWD" },
  { code: "UAH", name: "UAH" },
  { code: "SAR", name: "SAR" },
];

export const statuslist = [
  { code: "available", name: "Available" },
  { code: "sold out", name: "Sold out" },
];

export const adTypes = [
  { code: "sell", name: "Sell" },
  { code: "trade", name: "Trade" },
];

export const filterOptions = [
  { key: "platform", label: "Platform" },
  { key: "category", label: "Category" },
  { key: "minPrice", label: "MinPrice" },
  { key: "maxPrice", label: "MaxPrice" },
  { key: "currency", label: "Currency" },
  { key: "adType", label: "AdType" },
  { key: "status", label: "Status" },
  { key: "region", label: "Region" },
];
